name: Live Digital Clock Stream

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg python3 python3-pip
          pip install opencv-python numpy ffmpeg-python

      - name: Run Live Clock Script
        run: |
          nohup python3 clock_visualizer.py > clock_stream.log 2>&1 &
